# Generated by Django 4.2.19 on 2025-03-01 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SkinAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('skin_tone', models.CharField(max_length=50)),
                ('skin_type', models.CharField(max_length=50)),
                ('percentage', models.CharField(max_length=10)),
                ('acne_types', models.CharField(max_length=50)),
                ('redness_score', models.CharField(max_length=10)),
                ('pores_score', models.CharField(max_length=10)),
                ('pigmentation_score', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
